// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAIX85C_nml8Y4eocEjT5hov6pthMBugKM',
    appId: '1:652674484112:web:cae05eb5ce964c1bb3d515',
    messagingSenderId: '652674484112',
    projectId: 'smart-real-estate-67577',
    authDomain: 'smart-real-estate-67577.firebaseapp.com',
    storageBucket: 'smart-real-estate-67577.appspot.com',
    measurementId: 'G-NTFEQ6QD54',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAufER38rDyALBtTOG2cy8e5Iu-kuIGx9w',
    appId: '1:652674484112:android:fd42e5c7a149d120b3d515',
    messagingSenderId: '652674484112',
    projectId: 'smart-real-estate-67577',
    storageBucket: 'smart-real-estate-67577.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCpc2lhMDNL9KP8qivYH2h-s0Rzd-w4Oo0',
    appId: '1:652674484112:ios:858f48d3cc2b3de4b3d515',
    messagingSenderId: '652674484112',
    projectId: 'smart-real-estate-67577',
    storageBucket: 'smart-real-estate-67577.appspot.com',
    androidClientId: '652674484112-d7m0j74vse2irpq4q4un0tfvtv0e0a1u.apps.googleusercontent.com',
    iosClientId: '652674484112-u3jukeijs576uug422ib9h05fabc5p60.apps.googleusercontent.com',
    iosBundleId: 'com.example.smartRealEstateFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCpc2lhMDNL9KP8qivYH2h-s0Rzd-w4Oo0',
    appId: '1:652674484112:ios:ffb7445497ed1499b3d515',
    messagingSenderId: '652674484112',
    projectId: 'smart-real-estate-67577',
    storageBucket: 'smart-real-estate-67577.appspot.com',
    androidClientId: '652674484112-d7m0j74vse2irpq4q4un0tfvtv0e0a1u.apps.googleusercontent.com',
    iosClientId: '652674484112-gc4ea2s5iupq8kg3pgr4peqgt0l2e6lm.apps.googleusercontent.com',
    iosBundleId: 'com.example.smartRealEstateFirebase.RunnerTests',
  );
}
